{"uuid": "babc7be4-3a2a-4dee-b291-a7c262af6dd1", "stdout": "fatal: [192.168.122.162]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.122.162 port 22: No route to host\\r\\n\", \"unreachable\": true}", "counter": 5, "pid": 14776, "event_data": {"play_pattern": "all", "play": "all", "task": "Gathering Facts", "task_args": "_ansible_version=2.5.2, _ansible_selinux_special_fs=['fuse', 'nfs', 'vboxsf', 'ramfs', '9p'], _ansible_no_log=False, gather_timeout=10, _ansible_module_name=setup, _ansible_verbosity=0, _ansible_syslog_facility=LOG_USER, _ansible_socket=None, gather_subset=all, _ansible_diff=False, _ansible_debug=False, _ansible_shell_executable=/bin/sh, _ansible_check_mode=False, _ansible_tmpdir=None", "remote_addr": "192.168.122.162", "res": {"msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.122.162 port 22: No route to host\r\n", "unreachable": true, "changed": false}, "pid": 14776, "play_uuid": "54e1ada8-887a-ccaa-ba1c-000000000007", "task_uuid": "54e1ada8-887a-ccaa-ba1c-00000000000f", "playbook_uuid": "fb33b051-0421-498d-a34e-35fae7ed4196", "playbook": "main.yml", "task_action": "setup", "host": "192.168.122.162", "task_path": "/home/dpivonka/Documents/ansible_runner_testing/ansible/project/main.yml:3"}, "end_line": 6, "created": "2018-06-19T16:31:38.395350", "start_line": 5, "event": "runner_on_unreachable"}