{"uuid": "658643cc-3062-4fc0-8817-0b27d8a4b007", "stdout": "fatal: [all]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: Could not resolve hostname all: Name or service not known\\r\\n\", \"unreachable\": true}", "counter": 5, "pid": 15678, "event_data": {"play_pattern": "all", "play": "all", "task": "Gathering Facts", "task_args": "_ansible_version=2.5.2, _ansible_selinux_special_fs=['fuse', 'nfs', 'vboxsf', 'ramfs', '9p'], _ansible_no_log=False, gather_timeout=10, _ansible_module_name=setup, _ansible_verbosity=0, _ansible_syslog_facility=LOG_USER, _ansible_socket=None, gather_subset=all, _ansible_diff=False, _ansible_debug=False, _ansible_shell_executable=/bin/sh, _ansible_check_mode=False, _ansible_tmpdir=None", "remote_addr": "all", "res": {"msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname all: Name or service not known\r\n", "unreachable": true, "changed": false}, "pid": 15678, "play_uuid": "54e1ada8-887a-8c87-409b-000000000008", "task_uuid": "54e1ada8-887a-8c87-409b-00000000000f", "playbook_uuid": "85076534-da2d-40be-8d16-7a501d92aa99", "playbook": "main.yml", "task_action": "setup", "host": "all", "task_path": "/home/dpivonka/Documents/ansible_runner_testing/ansible/project/main.yml:3"}, "end_line": 6, "created": "2018-06-18T15:55:36.492981", "start_line": 5, "event": "runner_on_unreachable"}